language: python
python:
  - "3.7"
install: "pip install -r requirements.txt"
script: make clean coverage docs dist
deploy:
  provider: pypi
  user: "__token__"
  password: "pypi-AgEIcHlwaS5vcmcCJGQ5ZDhhOGVmLTQyMTYtNGRlOC05OGU1LTc0MTg2ZmUyNzFiNQACTnsicGVybWlzc2lvbnMiOiB7InByb2plY3RzIjogWyJyb2JvdGZyYW1ld29yay1qZW5raW5zbGlicmFyeSJdfSwgInZlcnNpb24iOiAxfQAABiAsHoiJts_M1Y9xHzfGUfFolBvn32UFv-l-4TviB0nhpQ"
  on:
    tags: true
    branch: master